<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Incio_module-icon fa fa-home</name>
   <tag></tag>
   <elementGuidId>26ffe2ad-e85f-41c4-8800-f32b1a0978cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.module-icon.fa.fa-home</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appM']/aside/div/div[2]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>module-icon fa fa-home</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appM&quot;)/aside[@class=&quot;l-left menu  active&quot;]/div[@class=&quot;links-wrapper --padding-bottom-20&quot;]/div[2]/a[@class=&quot;module-link&quot;]/i[@class=&quot;module-icon fa fa-home&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appM']/aside/div/div[2]/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div[2]/a/i</value>
   </webElementXpaths>
</WebElementEntity>
